In [2]:
import numpy as np

In [3]:
# a = np.array([[1,2,3,3,1],[6,8,11,10,7]])
# a.T
a = np.array([
    [1,6],[2,8],[3,11],[3,10],[1,7]
])
# a[:,1]
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [5]:
np.reshape(mean_a,(1,2))

array([[2. , 8.4]])

In [6]:
a_centered = a - np.reshape(mean_a,(1,2))
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
a_centered_sp = a[:,0] @ a[:,1]
a_centered_sp/(len(a[1]-1))
# a_centered_sp/(a[:,1].size - 1)

46.0

In [8]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [9]:
import pandas as pd

In [10]:
data ={'author_id':[1, 2, 3],'author_name':['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(data)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [11]:
book_data = {'author_id':[1, 1, 1, 2, 2, 3, 3],'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],'price':[450, 300, 350, 500, 450, 370, 290]}
book = pd.DataFrame(book_data)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [12]:
authors_price = pd.merge(book,authors,how='left',on='author_id')
top5 = authors_price.nlargest(5,'price')
authors_price

author_id            book_title  price author_name
0          1           Отцы и дети    450    Тургенев
1          1                 Рудин    300    Тургенев
2          1     Дворянское гнездо    350    Тургенев
3          2      Толстый и тонкий    500       Чехов
4          2       Дама с собачкой    450       Чехов
5          3                 Гроза    370  Островский
6          3  Таланты и поклонники    290  Островский

In [28]:

authors_stat = authors_price.groupby('author_name').agg({'min_price':'min','max_price':'max','mean_price':'mean'})

authors_stat

SpecificationError: Column(s) ['max_price', 'mean_price', 'min_price'] do not exist

In [32]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min','max','mean']})

authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

In [34]:

authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id            book_title  price author_name    cover
0          1           Отцы и дети    450    Тургенев  твердая
1          1                 Рудин    300    Тургенев   мягкая
2          1     Дворянское гнездо    350    Тургенев   мягкая
3          2      Толстый и тонкий    500       Чехов  твердая
4          2       Дама с собачкой    450       Чехов  твердая
5          3                 Гроза    370  Островский   мягкая
6          3  Таланты и поклонники    290  Островский   мягкая

In [41]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [42]:
book_info.to_pickle('book_info.pkl')

In [43]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info.equals(book_info2)

True